// src/config/sheetsConfig.ts
export const SHEETS_CONFIG = {
  SPREADSHEET_ID: import.meta.env.VITE_GOOGLE_SHEETS_SPREADSHEET_ID,
  SHEETS: {
    USERS: 'Users',
    ORDERS: 'Orders',
    ORDER_ITEMS: 'OrderItems',
    CUSTOMERS: 'Customers',
    PRODUCTS: 'Products',
    CARRIERS: 'Carriers',
    INBOUND_INTERNATIONAL: 'InboundInternational',
    INBOUND_DOMESTIC: 'InboundDomestic',
    PRICING: 'Pricing',
    ROUTES: 'Routes',
    SETTINGS: 'Settings',
  },
} as const;

export const USERS_HEADERS = [
  'id',
  'email',
  'passwordHash',
  'fullName',
  'roleId',
  'status',
  'createdAt',
  'updatedAt',
];

export const ORDERS_HEADERS = [
  'orderId',
  'customerName',
  'customerEmail',
  'customerPhone',
  'pickupAddress',
  'deliveryAddress',
  'pickupCoordinates',
  'deliveryCoordinates',
  'carrierId',
  'carrierName',
  'totalWeight',
  'totalVolume',
  'packageCount',
  'serviceLevel',
  'estimatedCost',
  'actualCost',
  'distance',
  'estimatedDuration',
  'status',
  'notes',
  'createdAt',
  'updatedAt',
  'scheduledPickup',
  'scheduledDelivery',
  'actualPickup',
  'actualDelivery',
];

export const CARRIERS_HEADERS = [
  'carrierId',
  'name',
  'contactPerson',
  'email',
  'phone',
  'address',
  'serviceAreas',
  'pricingMethod',
  'baseRate',
  'perKmRate',
  'perM3Rate',
  'perTripRate',
  'stopFee',
  'fuelSurcharge',
  'remoteAreaFee',
  'insuranceRate',
  'vehicleTypes',
  'maxWeight',
  'maxVolume',
  'operatingHours',
  'rating',
  'isActive',
  'createdAt',
  'updatedAt',
];

// Headers for InboundInternational sheet (flattened to map frontend fields)
// Complex arrays are stored as JSON strings for packaging/timeline/documentStatus
export const INBOUND_INTERNATIONAL_HEADERS = [
  'id',
  'date',
  'pi',
  'supplier',
  'origin',
  'destination',
  'product',
  'category',
  'quantity',
  'container',
  'status',
  'carrier',
  'purpose',
  'receiveTime',
  'poNumbers', // semicolon-separated
  // Packaging flattened
  'packagingTypes',
  'packagingQuantities',
  'packagingDescriptions',
  // Timeline flattened
  'timeline_cargoReady_est',
  'timeline_cargoReady_act',
  'timeline_cargoReady_status',
  'timeline_etd_est',
  'timeline_etd_act',
  'timeline_etd_status',
  'timeline_eta_est',
  'timeline_eta_act',
  'timeline_eta_status',
  'timeline_depart_est',
  'timeline_depart_act',
  'timeline_depart_status',
  'timeline_arrivalPort_est',
  'timeline_arrivalPort_act',
  'timeline_arrivalPort_status',
  'timeline_receive_est',
  'timeline_receive_act',
  'timeline_receive_status',
  // Document status flattened
  'doc_checkBill_est',
  'doc_checkBill_act',
  'doc_checkBill_status',
  'doc_checkCO_est',
  'doc_checkCO_act',
  'doc_checkCO_status',
  'doc_sendDocs_est',
  'doc_sendDocs_act',
  'doc_sendDocs_status',
  'doc_customs_est',
  'doc_customs_act',
  'doc_customs_status',
  'doc_tax_est',
  'doc_tax_act',
  'doc_tax_status',
  'notes',
  'createdAt',
  'updatedAt',
];

// Headers for InboundDomestic sheet (simplified structure)
export const INBOUND_DOMESTIC_HEADERS = [
  'id',
  'date',
  'supplier',
  'origin',
  'destination',
  'product',
  'quantity',
  'status',
  'category',
  'carrier',
  'purpose',
  'receiveTime',
  'notes',
  'createdAt',
  'updatedAt',
];
